### ISSUE TITLE
Bluebird instead of Q

### ISSUE THREAD

**Issue by knownasilya** [redradix/kontainer#1]
Bluebird has more features and is faster then Q.

http://calvinmetcalf.com/post/85041743853/comparing-promise-libraries

I can submit a PR if you are for switching it.

**Comment by fuzzyalej** [comment]
Seems like a good idea, thanks :)

**Comment by cdelaorden** [comment]
Hi @knownasilya 

I normally use bluebird actually, but for this simple case which is a single `Promise.all` I think we should eventually relay on ES2015 Promise.

**Comment by knownasilya** [comment]
I agree about eventually, but in the mean time, we still use libraries, at least until iojs is merged.

**Comment by cdelaorden** [comment]
Yes of course, but don't you think for a simple Promise.all Q is valid? Or is there anything else I'm missing? I'd like to know please :)

**Comment by knownasilya** [comment]
Q is the slowest promise library, so it doesn't matter if you only use one method, it's still the slowest, and since a container is involved in everything, performance is definitely important.

**Comment by cdelaorden** [comment]
Ok fair enough, I'll swap the Promise dependency and republish to npm. :+1:

**Comment by cdelaorden** [comment]
Done in 0.9.7
