### ISSUE TITLE
Support for PromisifyAll

### ISSUE THREAD

**Issue by sharathm** [redradix/kontainer#6]
Do you guys support `PromisifyAll`? 
I am trying  to write a service for Redis, and was thinking of using PromisifyAll so that I can have all my methods Asynced.

**Comment by cdelaorden** [comment]
Hi @sharathm I'm not sure I understand your question.

Your service can be all async of course, kontainer will only help you in producing that service. You can start modules that return a Promise, see the async example:
https://github.com/redradix/kontainer/tree/master/examples/async

**Comment by sharathm** [comment]
Got it!
