### ISSUE TITLE
Typescript Integration

### ISSUE THREAD

**Issue by Stingzor** [redradix/kontainer#8]
Hi,

I've been trying to implement this solution on a new project that uses typescript. 
Have you done this before? 

The only way I found to generate the correct "factory function" for the container to work was like this;

```
export function PingHandler(_pingService: IPingService) {
    const PingService = _pingService;
    return {
        ping() {
            return PingService.ping();
        }
    };
}
```

which produced:

```
'use strict';
function PingHandler(_pingService) {
    var PingService = _pingService;
    return {
        ping: function () {
            return PingService.ping();
        }
    };
}
exports.PingHandler = PingHandler;
```

The thing is, I'll lose Intellisense and Type Safety due to the lack of Interfaces and Classes implementation.

When generating it as a class:

```
import IPingService from './IPingService';

class PingService implements IPingService {
    ping() {
        return 'pong';
    }
}

export default PingService

```

the output is:

```

'use strict';
var PingService = (function () {
    function PingService() {
    }
    PingService.prototype.ping = function () {
        return 'pong';
    };
    return PingService;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = PingService;
```

The produced code cannot be used with this project, do you have an alternative?

Thank you

**Comment by cdelaorden** [comment]
Hi @Stingzor 
I'm not a Typescript user at all so this library is probably not going to work for you. This is for Javascript at the moment. 

Having said that, what's the problem with your first example? If you write it like this, it should work straightforward, shouldn't it?

``` javascript
export function PingHandlerFactory(PingService: IPingService) {
    return {
        ping() {
            return PingService.ping();
        }
    };
}
```

**Comment by Stingzor** [comment]
Hey @cdelaorden 

Since typescript is a superset of javascript, when I "compile" it, the output is in fact a javascript

In the first example, when exporting the PingHandler as a function and using it as a parameter on another call, I end up losing strongly typing, just like I had on the PingService parameter.

What I ended up doing was, I transpiled the Typescript code as ES2015 and it worked just the the example you provided.

If you wish i can provide you the full example.

```

import IPingService from './IPingService';
import IPingHandler from './IPingHandler';


class PingHandler implements IPingHandler {
    public PingService: IPingService;

    constructor(_pingService: IPingService) {
        this.PingService = _pingService;
    }

    public ping = (request: any, reply: any) => {

        reply({
            message: this.PingService.ping()
        })
    }
};

export = PingHandler;
```

which produced: 

```
'use strict';
class PingHandler {
    constructor(_pingService) {
        this.ping = (request, reply) => {
            reply({
                message: this.PingService.ping()
            });
        };
        this.PingService = _pingService;
    }
}
;
module.exports = PingHandler;
```

Thank you for your awesome work!

**Comment by cdelaorden** [comment]
Nice to hear you got it working! I'm closing the issue now as it seems there's nothing else we can do here.

Thanks for your support ;)
